### ISSUE TITLE
Add Default troubleshoot scenarios

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppServicesSupportCenterPortal#19] opened 2017-04-02 00:49 UTC

**Comment by ShekharGupta1988** [comment] 2017-04-03 17:19
Open Ticket component added as part of #28

**Comment by stevenernst131** [comment] 2017-04-26 22:27
Ignoring ticket opening, this is duplicate of #60

**Comment by ShekharGupta1988** [comment] 2017-05-16 21:21
@stevenernst131 - this can be closed now, right?

**Closed** 2017-05-16 21:37 UTC
Labels: FirstRelease, in progress
