### ISSUE TITLE
Application crashed but no details

### ISSUE THREAD

**Issue by cristhianu** [ShekharGupta1988/AppServicesSupportCenterPortal#76] opened 2017-04-26 18:49 UTC
My application crashed and reported a 500 error, the detector shows that My app is experiencing server errors but nothing is displayed under "Your app is unhealthy right now" under either More Details or Less Details.
![asc-bishopdefault5xxnodetails](https://cloud.githubusercontent.com/assets/7376302/25451230/146e2ba8-2a87-11e7-97c0-a79b363b7cd8.png)

**Comment by stevenernst131** [comment] 2017-04-26 19:18
Duplicate of #74

**Closed by stevenernst131** 2017-04-26 19:18 UTC
