### ISSUE TITLE
More details show empty response [BugBash]

### ISSUE THREAD

**Issue by prasadker** [ShekharGupta1988/AppServicesSupportCenterPortal#77] opened 2017-04-26 18:50 UTC
For my site myPortalEnabledJava, the Dashboard showed that "Your app is unhealthy" but it does not show any messages in the More details section.

![image](https://cloud.githubusercontent.com/assets/26941721/25451264/350034b0-2a87-11e7-87a0-acf0116ce39a.png)

**Comment by stevenernst131** [comment] 2017-04-26 19:18
Duplicate of #74

**Closed by stevenernst131** 2017-04-26 19:18 UTC
