### ISSUE TITLE
For HTTP 500 errors, should we adjust the ordering of the solutions?

### ISSUE THREAD

**Issue by MattTatoczenko** [ShekharGupta1988/AppServicesSupportCenterPortal#70] opened 2017-04-26 18:22 UTC
It seems odd to me that when getting HTTP 500 errors, I'm being told to restart my app first. I would expect that to be the last option. Wouldn't we want it to instead list out the application logs that a customer should look at instead? Here's the ordering I see:

![image](https://cloud.githubusercontent.com/assets/24440502/25450069/693241b4-2a83-11e7-875f-2a447cdd9d00.png)

**Comment by stevenernst131** [comment] 2017-04-26 22:13
We need to figure out which detector was giving these solutions or if they were generic solutions

**Comment by stevenernst131** [comment] 2017-04-26 22:14
Duplicate of #69

**Closed by stevenernst131** 2017-04-26 22:14 UTC
Labels: BUGBASH
