### ISSUE TITLE
Empty "Observations" shown along with "Your app is unhealthy right now"

### ISSUE THREAD

**Issue by gaurap** [ShekharGupta1988/AppServicesSupportCenterPortal#62] opened 2017-04-26 00:46 UTC
![image](https://cloud.githubusercontent.com/assets/12058025/25413433/e43eb3c2-29ef-11e7-9a2c-99b6f3a76555.png)

**Comment by stevenernst131** [comment] 2017-04-26 00:52
related to #42. Still need to handle this case. This happens when it was healthy but pulse is showing failures.

**Comment by stevenernst131** [comment] 2017-04-26 19:20
Duplicate of #74

**Closed by stevenernst131** 2017-04-26 19:20 UTC
Labels: BUGBASH
