### ISSUE TITLE
Date is incorrect in Application Analysis reporting 

### ISSUE THREAD

**Issue by madihahussain** [ShekharGupta1988/AppServicesSupportCenterPortal#72] opened 2017-04-26 18:34 UTC
Date is incorrect :  I see the date showing up as 3/3 - 3/2 

![image](https://cloud.githubusercontent.com/assets/6403741/25450570/e86f84c2-2a84-11e7-9429-2b8899f5cce4.png)

![image](https://cloud.githubusercontent.com/assets/6403741/25450612/0bafbfc4-2a85-11e7-88bd-b4d2cdc5c0c9.png)

**Comment by stevenernst131** [comment] 2017-04-26 19:24
Duplicate of #71

**Closed by stevenernst131** 2017-04-26 19:24 UTC
Labels: BUGBASH
